### ISSUE TITLE
Can't execute Mercurial binary

### ISSUE THREAD

**Issue by mrstebo** [victor-torres/atom-hg#11]
This is the same issue I got when I tried building the async repo yesterday.

![atom-hg-issue](https://cloud.githubusercontent.com/assets/3327152/14579636/45abc6a0-03a8-11e6-9cf5-df602b8c0961.png)

**Comment by victor-torres** [comment]
There's a related issue #5. Sorry about asking this, but do you have Mercurial binaries in your PATH environment variable?

**Comment by mrstebo** [comment]
Ah! Needed to reboot after installing mercurial! doh! :persevere:
