### ISSUE TITLE
No file diff in tree-view, incorrect line diff in text editor

### ISSUE THREAD

**Issue by bigslycat** [victor-torres/atom-hg#16]
1. All strokes are marked changed when file haven't changes and anyway.
2. Tree-view display without diff, when files have changes.

![2016-04-21 09 11 33](https://cloud.githubusercontent.com/assets/1121997/14697903/6c1f751a-07aa-11e6-8967-57b2e44e4cda.png)
- Atom
  - 1.7.1
  - 1.7.2
- Atom Hg
  - 2.0.3
  - 2.0.4
- node v5.10.1
- npm 3.8.0
- Ubuntu Trusty

**Comment by victor-torres** [comment]
Can you attach some debug logs and messages shown on Atom's developer console, please?

Sorry about asking, but do you have Mercurial installed and correctly configured in your PATH environment variable?

**Comment by bigslycat** [comment]
Yes, Mercurial is configured correctly. Problem is actual after last update Atom Hg.

```
Activating atom-hg...

/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

**Comment by victor-torres** [comment]
I'll ask a friend for help with reproducing this issue since I'm an OS X user and he's a Ubuntu user.

**Comment by leonascimento** [comment]
@victor-torres @figliohulio 
I did some tests and anything works well
- unbutu 14.04 lts
- Atom 1.4.3
- Atom Hg 2.0.4
- Node v5.10.1
- npm 3.8.3

**Comment by bigslycat** [comment]
This error does not depend on the environment. The reason is reported in #18 issue.
