### ISSUE TITLE
Working with symlink fail

### ISSUE THREAD

**Issue by bigslycat** [victor-torres/atom-hg#18]
Atom-hg does not work correctly when Mercurial repository opened in Atom as a symbolic link. This was reflected in #16 issue, but at that time I did not understand what the reason was.

**Comment by victor-torres** [comment]
Thanks for the report. Now we have something to work with :)

**Comment by victor-torres** [comment]
@bigslycat can you update to version 2.0.11 and try to open your project from a symlink again?
