### ISSUE TITLE
Ignored status not visible in the tree-view

### ISSUE THREAD

**Issue by sompylasar** [victor-torres/atom-hg#19]
The `hg status {rootPath}` command that is used to check the status returns only a subset of statuses by default, and it omits the `I` (ignore) status from its output.

https://github.com/victor-torres/atom-hg/blob/ba35b6a39b3ad0f5d574d58be7de7fd69fdd4e0d/lib/hg-utils.coffee#L296

The status [is handled by the code](https://github.com/victor-torres/atom-hg/blob/ba35b6a39b3ad0f5d574d58be7de7fd69fdd4e0d/lib/hg-utils.coffee#L385), but this code never triggers because of the above.

Please be aware though that the output of `hg status {rootPath} --all` which reports all the statuses may be quite large (e.g. the `node_modules` with a lot of files in it), so the handling should be somehow optimized / asynced to avoid blocking the UI.

**Comment by victor-torres** [comment]
Ignored files will be ignored by the plugin.

**Comment by sompylasar** [comment]
@victor-torres by which plugin?

**Comment by victor-torres** [comment]
`atom-hg` itself. I don't see any point in showing ignored files in the editor's tree. 

If you really really want it the only thing I could think about is checking if `Hide VCS ignored files` flag defined in Atom's preferences and stop ignoring files with the  "I" status if it's unchecked. What do you think?

Are you comfortable writing a pull request for this?

**Comment by sompylasar** [comment]
Looks like you don't understand what this issue is about. Currently it doesn't work as expected, the ignored files are shown and not marked as ignored, so they are included into the search across all files.

**Comment by victor-torres** [comment]
@sompylasar seems like @TomKemperNL have fixed your issue. I'm releasing a new version of the plugin right now so that you can validate the solution. If it doesn't work, please, reopen this issue. Thanks.

**Comment by sompylasar** [comment]
Wow these two fixes https://github.com/victor-torres/atom-hg/pull/25/commits/c8f8d73e79fa68f509efd3ca6035864bfc55eebd https://github.com/victor-torres/atom-hg/pull/25/commits/902abf2f93aec24de4c3c534531c94a0ee5f813b are really important ones!

I'll give it a try as soon as I get to the mercurial project with Atom.

@TomKemperNL Many thanks!
