### ISSUE TITLE
After commit, line and dir diff are not updating

### ISSUE THREAD

**Issue by FutoRicky** [victor-torres/atom-hg#2]
After committing, line and directory diffs stay the same. To be able to update I have to close the project in atom and load it up again.

**Comment by victor-torres** [comment]
Thanks for reporting, @FutoRicky. I'll take a look at this this week.

**Comment by victor-torres** [comment]
@FutoRicky could you try version 0.0.9 and tell me if its fixed, please?

**Comment by FutoRicky** [comment]
@victor-torres Seems like it's working now. I'll re-open if something comes up. Thanks!

**Comment by victor-torres** [comment]
@FutoRicky You're welcome :)
