### ISSUE TITLE
atom-hg causes Atom to freeze

### ISSUE THREAD

**Issue by goemaeret** [victor-torres/atom-hg#26]
I've been using this package for a while now, but after i've updated to the latest release (**atom-hg 2.0.8**) this morning it causes Atom to freeze and not respond for a couple of seconds when switching between applications. I temporarily disabled the package cause this is kind of annoying. Is it possible to look into this please?

**Atom Version**: 1.10.2
**System**: macOS Sierra (10.12)

Thx in advance

**Comment by victor-torres** [comment]
It’s been happening for a while since past versions of both Atom and atom-hg plugin. This relates with #21 and may be fixed by #15.
