### ISSUE TITLE
Mercurial hg-utils Error: no such file in rev

### ISSUE THREAD

**Issue by boozook** [victor-torres/atom-hg#4]
Firstly **thanks for this package**!

---

I have a couple of not-added untracked files.
- `SomeProject` is main Project Directory;
- `SomeProject/DIR/` is new & untracked folder;

Error log:

``` log
Mercurial hg-utils Error: ../Users/fzzr/Developer/Projects/SomeProject/DIR/foobar.js: no such file in rev 8a09e87cb36c(…)
Repository.handleHgError @ /Users/fzzr/.atom/packages/atom-hg/lib/hg-utils.coffee:268
```

**Problem:**

TreeView's UI get beak behaviour - I can't expand directory `DIR` in the tree.

![screen shot 2016-04-03 at 21 31 38](https://cloud.githubusercontent.com/assets/888526/14234117/ecfd8da6-f9eb-11e5-8756-5d24465ce528.png)

---

The message `no such file in rev` isn't an error. It's about "this file is not added and untracked".

You need to call `hg status` for get status for **all** files including untracked/not-added.

**Comment by victor-torres** [comment]
Thanks for your report. I'll take a look as soon as possible.

If you feel comfortable about writing and submitting a pull request, you're welcome.

**Comment by victor-torres** [comment]
@fzzr- could you try version 0.0.9 and tell me if its fixed, please?

**Comment by boozook** [comment]
Updated. Thanks, it works!

**Comment by victor-torres** [comment]
@fzzr- You're welcome :smile:
