### ISSUE TITLE
Support for Atom 1.7

### ISSUE THREAD

**Issue by mrstebo** [victor-torres/atom-hg#9]
[Atom 1.7](http://blog.atom.io/2016/03/17/atom-1-6-and-1-7-beta.html) has introduced async repositories. An error occurrs on [this line](https://github.com/atom/status-bar/blob/master/lib/git-view.coffee#L70) on the status-bar package because we are missing an async respository.

It mentions that they will be depreciating the GitRepository so I am attempting to write an async version of the HgRepository.

[Here is how atom currently adds the async repository.](https://github.com/atom/atom/blob/39592599b1f577a0d395a088ecea3293d159097d/src/git-repository.coffee#L84)

**Comment by victor-torres** [comment]
I had those tabs opened when you created this issue. It was the first thing I saw when I first opened Atom today. Are you planning in write another pull request for this?

**Comment by victor-torres** [comment]
This would help @BlaM with his issue #3

**Comment by victor-torres** [comment]
I'm working on it.

**Comment by victor-torres** [comment]
The plugin is working again, but I'm having some troubles with tree-view. Hope in an hour it's solved.

**Comment by mrstebo** [comment]
Yeah sorry, I have created a `HgRepositoryAsync` class, but doesn't seem to be working yet...but no errors popping up :fearful:

**Comment by victor-torres** [comment]
Lets keep running together.

**Comment by mrstebo** [comment]
Agreed! Won't have chance to work on it tonight. But I'll have another go at it tomorrow at some point

**Comment by victor-torres** [comment]
@mrstebo can you checkout the async branch and test it on your machine before we release version 2.0.0 please?

**Comment by mrstebo** [comment]
Sure. I'll give it a test in the morning and let you know how things go. The big test will be if it works on my work machine. Some nice big repos on there :grin:

**Comment by mrstebo** [comment]
Looks nice! Pretty much how I coded it 😄.  Unfortunately I left my code in the office 😩.

**Comment by victor-torres** [comment]
Nice @mrstebo. I'll just release version 2.0.0 and if you find any bug or have an enhancement tomorrow it could be released in the next 2.0.1 version or sth. like that. Thanks for your support once again.
